name: Build and Publish
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build extension
        run: npm run build

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: build.zip
          extension-id: ilgbbbhicjkjoojifihdbfeagpmmemlo
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
